name: fluto_core
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://flutter.dev"

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  draggable_widget: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  http: ^1.2.2
  package_info_plus:
  flutter_bloc: ^8.1.6
  cuberto_bottom_bar: ^3.1.0
  share_plus: ^10.1.2
  clipboard: ^0.1.3
  supabase_flutter: ^2.8.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner:

flutter:
  assets:
    - .env
